### PR TITLE
Standardjs installation and running 

### PR DESCRIPTION
**Pull request by lexik04**
Installation

Screenshot 2024-10-23 at 3 08 36 PM

Example Code that breaks many rules(Generated by chatGPT)
```
function add(a, b) {
    return a + b
  }
  
  function isEven(num) {
    return num % 2 === 0
  }
  

  const numbers = [1, 2, 3, 4, 5]
  const evenNumbers = numbers.filter(isEven)
  
  console.log('Even numbers:', evenNumbers)
  

  for (let i = 0; i < numbers.length; i++) {
    console.log(`Number ${numbers[i]} is ${isEven(numbers[i]) ? 'even' : 'odd'}`)
  }
```

Test:

```
lexikronowitz@lexis-air nodebb-f24-team-tbd-1 % npx standard test/standardjs.js
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:2:10: 'add' is defined but never used. (no-unused-vars)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:2:13: Missing space before function parentheses. (space-before-function-paren)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:3:1: Expected indentation of 2 spaces but found 4. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:4:1: Expected indentation of 0 spaces but found 2. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:5:1: Trailing spaces not allowed. (no-trailing-spaces)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:6:1: More than 1 blank line not allowed. (no-multiple-empty-lines)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:7:1: Expected indentation of 0 spaces but found 2. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:7:18: Missing space before function parentheses. (space-before-function-paren)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:8:1: Expected indentation of 2 spaces but found 4. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:9:1: Expected indentation of 0 spaces but found 2. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:10:1: Trailing spaces not allowed. (no-trailing-spaces)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:11:1: More than 1 blank line not allowed. (no-multiple-empty-lines)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:12:1: Expected indentation of 0 spaces but found 2. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:13:1: Expected indentation of 0 spaces but found 2. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:14:1: Trailing spaces not allowed. (no-trailing-spaces)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:15:1: Expected indentation of 0 spaces but found 2. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:16:1: Trailing spaces not allowed. (no-trailing-spaces)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:17:1: More than 1 blank line not allowed. (no-multiple-empty-lines)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:18:1: Expected indentation of 0 spaces but found 2. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:19:1: Expected indentation of 2 spaces but found 4. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:20:1: Expected indentation of 0 spaces but found 2. (indent)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:21:1: Trailing spaces not allowed. (no-trailing-spaces)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:21:1: Too many blank lines at the end of file. Max of 0 allowed. (no-multiple-empty-lines)
  /Users/lexikronowitz/Desktop/fse313/nodebb-f24-team-tbd-1/test/standardjs.js:21:3: Newline required at end of file but not found. (eol-last)
```
Screenshot 2024-10-23 at 3 16 50 PM

Added script to package.json

Screenshot 2024-10-24 at 11 12 04 PM

Standard Dependency
Screenshot 2024-10-24 at 11 12 58 PM

**After calling npx standard --fix on the file to automatically fix the code (only manually removed the unused variable 'add' function:**

```
function isEven (num) {
  return num % 2 === 0
}

const numbers = [1, 2, 3, 4, 5]
const evenNumbers = numbers.filter(isEven)

console.log('Even numbers:', evenNumbers)

for (let i = 0; i < numbers.length; i++) {
  console.log(`Number ${numbers[i]} is ${isEven(numbers[i]) ? 'even' : 'odd'}`)
}
```

Now calling npx standard we can see that it fixed all the errors expect the unused variable error:
Screenshot 2024-10-29 at 8 28 36 PM

### CODE REVIEW

**Review by vsolskyyy — COMMENTED** [review]
Very detailed tests to ensure the tool works as expected. It exposes the errors in the code.

**Comment by KevnKey** [comment]
The test looks to be working fine and the example code definitely shows the errors.

**Review by ay0503 — APPROVED** [review]
Might need to fix the linting issues for the deployment pipeline but otherwise lgtm!

**Review by ay0503 — APPROVED** [review]
really detailed love it.
nit: if we are going to merge though we want to get rid of the lining issues!

**Comment by KevnKey** [comment]
This is great info showing how it runs and even fixes errors automatically, especially for everything except unused variable. It should be good to say it has been run at least once in the git flow cycle.

**Review by ay0503 — COMMENTED** [review]
I just added the StandardJS workflow. It seems that because we have added the static tool to the codebase without changing the codebase to this StandardJS linting standards, the pipeline isn't passing. We can't push unless it passes, but at the same time I see more than 7000 lines of code that needs to be fixed. I tried the automatic formatted but it also seems we have some undefined/null prevention linting rules that we can't automatically fix. It also seems unfeasible for us to go through every line and fix them given the codebase is already so big.

**Comment by ay0503** [comment]
It looks like the standard linter was running on all files. I changed it to only work on the single file we created to get it to pass the pipelines.

**Pull request merged**
